id: P21429C04
initial_creation_type: ocr
source_metadata:
  volumes:
    1efa0a8346c041eabebf9ec998b362e8:
      base_file: v052.txt
      image_group_id: I1PD95897
      title: ཤེས་རབ་ཀྱི་ཕ་རོལ་ཏུ་ཕྱིན་པའི་མན་ངག་གི་བསྟན་བཅོས་མངོན་པར་རྟོགས་པའི་རྒྱན་ཞེས་བྱ་བའི་འགྲེལ་པ།
      total_pages: 1426
      volume_number: 52
